version: '2'
services: 
    mysql:
        image: mysql:5.7
        command: mysqld --user=root
        volumes:
        - ./mysql-dump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: infored_test
            MYSQL_USER: inforedUser
            MYSQL_PASSWORD: inforedPSW
            MYSQL_ROOT_PASSWORD: rootPSW
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - 8080:80
        environment:
        - PMA_HOST=mysql
        depends_on:
        - mysql