version: '2'
services: 
    mysql:
        image: mysql:5.7
        command: mysqld --user=root
        volumes:
        - ./mysql-dump:/docker-entrypoint-initdb.d
        restart: always
        ports:
        - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: infored_db
            MYSQL_USER: infored_user
            MYSQL_PASSWORD: infored_password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - 8080:80
        environment:
        - PMA_HOST=mysql
        depends_on:
        - mysql